#!/usr/bin/env ruby
require 'lib/momomoto/momomoto'
require 'lib/momomoto/tables/ui_message'
require 'lib/momomoto/bot_login'
require 'yaml'

Momomoto::Base.connect(YAML.load_file('config/database.yml')['production'])
Momomoto::Bot_login.authorize('ui_tagger')

def traverse_directory( directory )
  views = Dir.new( directory )
  views.each do | entry |
    next if entry == '.' || entry == '..'
    if File.directory?( directory + '/' + entry )
      traverse_directory( directory + '/' + entry )
    elsif entry.match(/^.*\.rhtml$/)
      # found a template file
      template = File.open( directory + '/' + entry )
      # puts "opened file: #{entry}"
      template.each_line do | line |
        if line.match(/<\[([a-z:_]+)\]>/)
          @tags.push( $1 )
        end
      end
      template.close
    else
      #puts "ignoring file: #{entry}"
    end
  end
end

@tags = []
traverse_directory('app/views')

ui_message = Momomoto::Ui_message.new
if @tags.length > 0
  @tags.each do | tag |
    ui_message.find({:tag => tag})
    if ui_message.nil?
      # tag does not yet exist
      puts "Add tag '#{tag}'?" 
      answer = gets
      if answer.match(/[Yy](es)?/)
        puts "adding tag: #{tag}"
        ui_message.create
        ui_message.tag = tag
        ui_message.write
      end
    end
  end
end

