#!/usr/bin/env ruby

require File.dirname(__FILE__) + '/../config/boot'
require File.dirname(__FILE__) + '/../config/environment'

require 'action_controller/integration'
require 'lib/html_export'

require 'application'
class ApplicationController < ActionController::Base
  def auth
    true
  end
end

class ActionController::Base
  alias_method :url_for_rails, :url_for
  def url_for(*args)
    HTMLExport.url_for( *args )
  end
end

conf = Conference.select_single(:acronym=>ARGV[0])
languages = View_conference_language.select(:conference_id=>conf.conference_id,:translated_id=>120)
languages = languages.map do | l | l.tag end
languages << 'en' if languages.length < 1

HTMLExport.init(conf)
HTMLExport.build_tree
languages.each do | lang |
  HTMLExport.export(:controller=>'schedule',:conference=>conf.acronym,:action=>:index,:language=>lang)
end

while HTMLExport.urls[0]
  current_url = HTMLExport.urls[0]
  HTMLExport.urls.delete( current_url )
  HTMLExport.export( current_url )
end

exit 0

