#!/usr/bin/env ruby

require 'config/environment.rb'
require 'lib/pentacards'

if ARGV.length != 1
  puts "Usage: #{$0} <conference-acronym>"
  exit
end

conference = Conference.select_single({:acronym=>ARGV[0]})

# find all events
events = View_find_event.select({:translated_id => 144, :conference_id => conference.conference_id})

puts "creating pentacards for #{events.length} events"

pc = Pentacards.new( events, 2, 2 )

File.open("pentacards.pdf", "wb") do |f|
  f.write( pc.render )
end

