#!/bin/sh
#
# Copyright (C) 2005 Luciano Bello
# Copyright (C) 2006 Joerg Jaspert
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2 dated June,
# 1991.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
#
# Graph Propousals

# DB, User and password to comas db
source /etc/munin/database.conf

if [ "$1" = "config" ]; then
	echo graph_title Proposals by type
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel proposals'
	echo 'graph_category Pentabarf'
	echo 'graph_info Shows proposals by type.'

	echo "total.label total"
	echo "total.info Total proposals."
	echo 'total.draw AREA'

	echo "panel.label panel"
	echo "panel.info Panel discussion"
	echo 'panel.draw LINE2'

	echo "workshop.label workshop"
	echo "workshop.info Workshop proposal"
	echo 'workshop.draw LINE2'

	echo "meeting.label meeting"
	echo "meeting.info Informal meeting"
	echo 'meeting.draw LINE2'

	echo "bof.label bof"
	echo "bof.info Open discussion (BoF)"
	echo 'bof.draw LINE2'

	echo "lecture.label lecture"
	echo "lecture.info Lecture"
	echo 'lecture.draw LINE2'

	echo "other.label other"
	echo "other.info Other"
	echo 'other.draw LINE2'

	echo "movie.label movie"
	echo "movie.info Film"
	echo 'movie.draw LINE2'

	echo "lightning.label lightning"
	echo "lightning.info Lightning talk"
	echo 'lightning.draw LINE2'

	echo "contest.label contest"
	echo "contest.info Contest"
	echo 'contest.draw LINE2'

	exit 0
fi

conf_id=2

panel=`psql -Atc "SELECT COUNT(event_id) FROM event WHERE event_type='podium' AND conference_id=$conf_id" $PGDB`
workshop=`psql -Atc "SELECT COUNT(event_id) FROM event WHERE event_type='workshop' AND conference_id=$conf_id" $PGDB`
meeting=`psql -Atc "SELECT COUNT(event_id) FROM event WHERE event_type='meeting' AND conference_id=$conf_id" $PGDB`
bof=`psql -Atc "SELECT COUNT(event_id) FROM event WHERE event_type='bof' AND conference_id=$conf_id" $PGDB`
lecture=`psql -Atc "SELECT COUNT(event_id) FROM event WHERE event_type='lecture' AND conference_id=$conf_id" $PGDB`
other=`psql -Atc "SELECT COUNT(event_id) FROM event WHERE event_type='other' AND conference_id=$conf_id" $PGDB`
movie=`psql -Atc "SELECT COUNT(event_id) FROM event WHERE event_type='movie' AND conference_id=$conf_id" $PGDB`
lightning=`psql -Atc "SELECT COUNT(event_id) FROM event WHERE event_type='lightning' AND conference_id=$conf_id" $PGDB`
contest=`psql -Atc "SELECT COUNT(event_id) FROM event WHERE event_type='contest' AND conference_id=$conf_id" $PGDB`

total=$((panel+workshop+meeting+bof+lecture+other+movie+lightning+contest))

echo "panel.value $panel" 
echo "workshop.value $workshop" 
echo "meeting.value $meeting" 
echo "bof.value $bof" 
echo "lecture.value $lecture" 
echo "other.value $other" 
echo "movie.value $movie" 
echo "lightning.value $lightning" 
echo "contest.value $contest" 
echo "total.value $total" 

