#!/bin/sh
#
# Copyright (C) 2005 Luciano Bello
# Copyright (C) 2006 Joerg Jaspert
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2 dated June,
# 1991.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
#
# Graph Propousals

# DB, User and password to comas db
source /etc/munin/database.conf

if [ "$1" = "config" ]; then
	echo graph_title Proposals by status
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel proposals'
	echo 'graph_category Pentabarf'
	echo 'graph_info Shows proposals by status.'

	echo "total.label total"
	echo "total.info Total proposals."
	echo 'total.draw AREA'

	echo "undecided.label undecided"
	echo "undecided.info Proposals in status 'Undecided'."
	echo 'undecided.draw LINE2'

	echo "rejected.label rejected"
	echo "rejected.info Proposals in status 'Rejected'."
	echo 'rejected.draw LINE2'

	echo "accepted.label accepted"
	echo "accepted.info Proposals in status 'Accepted'."
	echo 'accepted.draw LINE2'

	exit 0
fi

conf_id=2

undecided=`psql -Atc "SELECT COUNT(event_id) FROM event WHERE event_state='undecided' AND conference_id=$conf_id" $PGDB`
accepted=`psql -Atc "SELECT COUNT(event_id) FROM event WHERE event_state='accepted' AND conference_id=$conf_id" $PGDB`
rejected=`psql -Atc "SELECT COUNT(event_id) FROM event WHERE event_state='rejected' AND conference_id=$conf_id" $PGDB`

total=$((undecided+accepted+rejected))

echo "undecided.value $undecided" 
echo "rejected.value $rejected" 
echo "accepted.value $accepted" 
echo "total.value $total" 

