#!/bin/sh
#
# Copyright (C) 2005 Luciano Bello
# Copyright (C) 2006,2008 Joerg Jaspert
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2 dated June,
# 1991.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
#
# Graph travel money
#
# DB, User and password to comas db
source /etc/munin/database.conf

if [ "$1" = "config" ]; then
	echo graph_title Travel money
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel Amount'
	echo 'graph_category Pentabarf'
	echo 'graph_info Shows travel money.'

	echo "fares.label Travel fares total"
	echo "fares.info All Travel fares in total."
	echo 'fares.draw LINE2'

	echo "reque.label Requested sponsorship"
	echo "reque.info Requested sponsorship"
	echo 'reque.draw LINE2'

	exit 0
fi

fares=`psql -Atc 'SELECT sum(travel_cost) FROM conference_person_travel, debconf.dc_conference_person WHERE conference_person_id = person_id AND conference_id=2 AND attend IS TRUE;' $PGDB`

reque=`psql -Atc 'SELECT sum(fee) FROM conference_person_travel, debconf.dc_conference_person WHERE conference_person_id = person_id AND conference_id=2 AND attend IS TRUE;' $PGDB`

echo "fares.value $fares" 
echo "reque.value $reque" 

