#!/usr/bin/env ruby

database = 'pentabarf'
user = 'backup'
tables = ["authorisation", "authorisation_localized", "conference_phase", "conference_phase_localized", "country", "country_localized", "currency", "currency_localized", "event_role", "event_role_localized", "event_role_state", "event_role_state_localized", "event_state", "event_state_localized", "event_state_progress", "event_state_progress_localized", "event_type", "event_type_localized", "language", "language_localized", "link_type", "link_type_localized", "role", "role_localized", "role_authorisation", "time_zone", "time_zone_localized", "transport", "transport_localized", "ui_message", "ui_message_localized", "conflict_level", "conflict_level_localized", "conflict_type", "conflict", "conflict_localized", "conference_phase_conflict", "attachment_type", "attachment_type_localized"]


import = File.open('import.sql', 'w')
tables.each do | table | 
  puts "dumping table #{table}"
  system("pg_dump #{database} -a -D -O -x -U #{user} -t #{table} > #{table}.sql")
  import.puts("\\i #{table}.sql")
end


