#!/usr/bin/env ruby

require 'yaml'

db_config_file = File.dirname(__FILE__) + "/../../rails/config/database.yml"
db_config      = YAML.load_file db_config_file
db_production  = db_config['production']

ENV['PGHOST']     = db_production['host']
ENV['PGDATABASE'] = db_production['database']
ENV['PGUSER']     = db_production['username']
ENV['PGPASSWORD'] = db_production['password']
ENV['PGPORT']     = db_production['port'].to_s

tables = ["auth.domain", "auth.object_domain", "language", "language_localized", "authorisation", "authorisation_localized", "conference_phase", "conference_phase_localized", "country", "country_localized", "currency", "currency_localized", "event_role", "event_role_localized", "event_role_state", "event_role_state_localized", "event_state", "event_state_localized", "event_state_progress", "event_state_progress_localized", "event_type", "event_type_localized", "link_type", "link_type_localized", "role", "role_localized", "role_authorisation", "time_zone", "time_zone_localized", "transport", "transport_localized", "ui_message", "ui_message_localized", "conflict_level", "conflict_level_localized", "conflict_type", "conflict", "conflict_localized", "conference_phase_conflict", "attachment_type", "attachment_type_localized", "event_origin", "event_origin_localized", "mime_type", "mime_type_localized", "phone_type", "phone_type_localized", "im_type", "im_type_localized" ]

import = File.open('import.sql', 'w')
import.puts("BEGIN TRANSACTION;")
tables.each do | table |
  puts "dumping table #{table}"
  system("pg_dump -i -a -D -O -x -t #{table} -f #{table}.sql")

  # remove lines not understood by PostgreSQL < 8.2
  system("sed -i -e :a -e '/^SET standard_conforming_strings = off;$/N; s/.*\\\n//; ta' #{table}.sql")
  system("sed -i -e :a -e '/^SET escape_string_warning = off;$/N; s/.*\\\n//; ta' #{table}.sql")

  import.puts("\\i #{table}.sql")
end
import.puts("COMMIT TRANSACTION;")


