require 'views-conflict/view_conflict_attendee'
require 'views-conflict/view_conflict_person'
require 'views-conflict/view_conflict_event'
require 'views-conflict/view_conflict_event_event'
require 'views-conflict/view_conflict_event_person'
require 'views-conflict/view_conflict_event_person_event'
