
CREATE TABLE language (
  language_id SERIAL NOT NULL,
  iso_639_code CHAR(3) NOT NULL UNIQUE,
  tag VARCHAR(32) NOT NULL UNIQUE,
  f_default BOOL NOT NULL DEFAULT FALSE,
  f_localized BOOL NOT NULL DEFAULT FALSE,
  f_visible BOOL NOT NULL DEFAULT FALSE,
  f_preferred BOOL NOT NULL DEFAULT FALSE,
  PRIMARY KEY (language_id)
) WITHOUT OIDS;

