
CREATE TABLE person_travel (
  person_id INTEGER NOT NULL,
  conference_id INTEGER NOT NULL,
  arrival_transport_id INTEGER NOT NULL,
  arrival_from VARCHAR(64),
  arrival_to VARCHAR(64),
  arrival_number VARCHAR(32),
  arrival_date DATE,
  arrival_time TIME(0) WITH TIME ZONE,
  f_arrival_pickup BOOL NOT NULL DEFAULT FALSE,
  f_departure_pickup BOOL NOT NULL DEFAULT FALSE,
  departure_transport_id INTEGER NOT NULL,
  departure_from VARCHAR(64),
  departure_to VARCHAR(64),
  departure_number VARCHAR(32),
  departure_date DATE,
  departure_time TIME(0) WITH TIME ZONE,
  travel_cost DECIMAL(16,2),
  travel_currency_id INTEGER NOT NULL,
  accommodation_cost DECIMAL(16,2),
  accommodation_currency_id INTEGER NOT NULL,
  accommodation_name VARCHAR(64),
  accommodation_street VARCHAR(64),
  accommodation_postcode VARCHAR(10),
  accommodation_city VARCHAR(64),
  accommodation_phone VARCHAR(32),
  accommodation_phone_room VARCHAR(32),
  f_arrived BOOL NOT NULL DEFAULT FALSE,
  fee DECIMAL(16,2),
  fee_currency_id INTEGER NOT NULL,
  f_need_travel_cost BOOL NOT NULL DEFAULT FALSE,
  f_need_accommodation BOOL NOT NULL DEFAULT FALSE,
  f_need_accommodation_cost BOOL NOT NULL DEFAULT FALSE,
  last_modified TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  last_modified_by INTEGER,
  FOREIGN KEY (person_id) REFERENCES person (person_id) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (conference_id) REFERENCES conference (conference_id) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (arrival_transport_id) REFERENCES transport (transport_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (departure_transport_id) REFERENCES transport (transport_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (travel_currency_id) REFERENCES currency (currency_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (accommodation_currency_id) REFERENCES currency (currency_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (fee_currency_id) REFERENCES currency (currency_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (last_modified_by) REFERENCES person (person_id) ON UPDATE CASCADE ON DELETE SET NULL,
  PRIMARY KEY (person_id, conference_id)
);

