# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require(File.join(File.dirname(__FILE__), 'config', 'boot'))

require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

require 'rcov/rcovtask'

Rcov::RcovTask.new do | t |
  t.rcov_opts << '--xrefs'
  t.rcov_opts << '--comments'
  t.rcov_opts << '--rails'
#  t.rcov_opts << '-x /usr/local/lib/site_ruby/*'
  t.test_files = FileList['test/*/*_test.rb']
end

require 'tasks/rails'
