\i functions/auth/user_permissions.sql
\i functions/auth/activate_account.sql
\i functions/auth/hash_password.sql
\i functions/auth/create_account.sql
\i functions/auth/forgot_password.sql
\i functions/account/own_conference_persons.sql
\i functions/account/own_events.sql
\i functions/account/reset_password.sql
\i functions/add_attendee.sql
\i functions/admin/merge_person.sql
\i functions/admin/remove_conference.sql
\i functions/admin/remove_event.sql
\i functions/conflict/event/abstract_length.sql
\i functions/conflict/event/accepted_without_timeslot.sql
\i functions/conflict/event/conference_language.sql
\i functions/conflict/event/conflict_event.sql
\i functions/conflict/event/description_length.sql
\i functions/conflict/event_event/conflict_event_event.sql
\i functions/conflict/event_event/duplicate_tag.sql
\i functions/conflict/event_event/time.sql
\i functions/conflict/event/incomplete.sql
\i functions/conflict/event/inconsistent_public_link.sql
\i functions/conflict/event/inconsistent_tag.sql
\i functions/conflict/event/missing_tag.sql
\i functions/conflict/event/no_abstract.sql
\i functions/conflict/event/no_coordinator.sql
\i functions/conflict/event/no_description.sql
\i functions/conflict/event/no_language_sql.sql
\i functions/conflict/event/no_paper.sql
\i functions/conflict/event/no_slides.sql
\i functions/conflict/event/no_speaker.sql
\i functions/conflict/event/no_track.sql
\i functions/conflict/event/paper_unknown.sql
\i functions/conflict/event_person/conflict_event_person.sql
\i functions/conflict/event_person/event_after_departure.sql
\i functions/conflict/event_person/event_before_arrival.sql
\i functions/conflict/event_person/person_availability.sql
\i functions/conflict/event_person_event/conflict_event_person_event.sql
\i functions/conflict/event_person_event/time_attendee.sql
\i functions/conflict/event_person_event/time_speaker_speaker.sql
\i functions/conflict/event_person_event/time_speaker_visitor.sql
\i functions/conflict/event_person_event/time_visitor_visitor.sql
\i functions/conflict/event_person/language.sql
\i functions/conflict/event/slides_unknown.sql
\i functions/conflict/event/unconfirmed_with_timeslot.sql
\i functions/conflict/person/abstract_length.sql
\i functions/conflict/person/conflict_person.sql
\i functions/conflict/person/description_length.sql
\i functions/conflict/person/inconsistent_public_link.sql
\i functions/conflict/person/no_abstract.sql
\i functions/conflict/person/no_description.sql
\i functions/conflict/person/no_mail.sql
\i functions/copy_event.sql
\i functions/related_event_keyword.sql
\i functions/related_event_speaker.sql
\i functions/remove_attendee.sql
\i functions/submit_event.sql
