\i views-localization.sql
\i views/person.sql
\i views/conference_image_modification.sql
\i views/conference_image.sql
\i views/conference_person_link_internal.sql
\i views/conference_person.sql
\i views/conference_persons.sql
\i views/event_attachment.sql
\i views/event_image_modification.sql
\i views/event_image.sql
\i views/event_link_internal.sql
\i views/event_person_simple_person.sql
\i views/event_person.sql
\i views/event_rating_public.sql
\i views/event_rating.sql
\i views/event_related.sql
\i views/event.sql
\i views/find/event_search_persons.sql
\i views/find/find_conference.sql
\i views/find/find_event.sql
\i views/find/find_person.sql
\i views/jid_login.sql
\i views/last_active.sql
\i views/mail/mail_accepted_speaker.sql
\i views/mail/mail_all_reviewer.sql
\i views/mail/mail_all_speaker.sql
\i views/mail/mail_missing_slides.sql
\i views/person_image_modification.sql
\i views/person_image.sql
\i views/person_rating.sql
\i views/recent_changes.sql
\i views/report/report_arrived.sql
\i views/report/report_events.sql
\i views/report/report_expenses.sql
\i views/report/report_feedback.sql
\i views/report/report_missing.sql
\i views/report/report_paper.sql
\i views/report/report_pickup.sql
\i views/report/report_resources.sql
\i views/report/report_schedule_coordinator.sql
\i views/report/report_schedule_gender.sql
\i views/review.sql
\i views/schedule/schedule_event.sql
\i views/schedule/schedule_person.sql
\i views/schedule/schedule.sql
\i views/schedule/schedule_simple.sql
\i views/conference_rating.sql
\i views/event_feedback.sql

